In [76]:
import numpy as np
import pandas as pd

import sklearn

from sklearn.naive_bayes import GaussianNB
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score


from sklearn.metrics import confusion_matrix,classification_report

In [77]:
df= pd.read_csv('iris.csv',names=['sepal length in cm','sepal width in cm ','petal length in cm','petal width in cm','class'])
print('QUESTION 1')
print('Here I have read the iris data set as a csv into jupyter notebook.')

QUESTION 1
Here I have read the iris data set as a csv into jupyter notebook.


In [78]:
df.head()

sepal length in cm  sepal width in cm   petal length in cm  \
0                 5.1                 3.5                 1.4   
1                 4.9                 3.0                 1.4   
2                 4.7                 3.2                 1.3   
3                 4.6                 3.1                 1.5   
4                 5.0                 3.6                 1.4   

   petal width in cm        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa

In [79]:
X = df.drop('class', axis=1)

y = df['class']

In [80]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=1)

In [81]:
print('QUESTION 2')
print('Here we have created our Gaussian Naive Bayes Model')
print('')
Gauss = GaussianNB()

Gauss.fit(X_train, y_train)
print(Gauss)

y_expect = y_test
y_pred = Gauss.predict(X_test)

print (accuracy_score(y_expect, y_test))
print('')
print('QUESTION 3')
print('')
print('The accuracy score is 1.0 = 100%')
print('')
print('Other metrics used include:')
print('1. Classification Report - which is used below')
print('2. Classification Accuracy')
print('3. Area under ROC Curve')
print('4. Logarithmic Loss')
print('')

QUESTION 2
Here we have created our Gaussian Naive Bayes Model

GaussianNB(priors=None)
1.0

QUESTION 3

The accuracy score is 1.0 = 100%

Other metrics used include:
1. Classification Report - which is used below
2. Classification Accuracy
3. Area under ROC Curve
4. Logarithmic Loss



In [82]:
print('QUESTION 4')
print('')
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))
print('')
print('The confusion matrix shows how many instances were classified correctly. Leading diagonal shows correct classification and values outside the said diagonal show wrong classification.')
print('In our model,')
print('')
print('All 17 Iris-setosa were classified correctly')
print('17 Iris-versicolor were classified correctly and 2 were classified wrongly as Iris-virginica')
print('13 Iris-virginica were classified correctly and 1 was classified wrongly as Iris-versicolor')

QUESTION 4

Confusion Matrix
[[17  0  0]
 [ 0 17  2]
 [ 0  1 13]]

The confusion matrix shows how many instances were classified correctly. Leading diagonal shows correct classification and values outside the said diagonal show wrong classification.
In our model,

All 17 Iris-setosa were classified correctly
17 Iris-versicolor were classified correctly and 2 were classified wrongly as Iris-virginica
13 Iris-virginica were classified correctly and 1 was classified wrongly as Iris-versicolor


In [83]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        17
Iris-versicolor       0.94      0.89      0.92        19
 Iris-virginica       0.87      0.93      0.90        14

    avg / total       0.94      0.94      0.94        50



In [84]:
print('')
print('QUESTION 5')
print('Naive Bayes makes the following assumption:')
print('')
print('Attribute Independence: It assumes that the presence of a particular feature in a class is unrelated to the presence of any other feeture. ')
print('         For example, a fruit may be considered a banana if it is elongated and yellow. Even if these attributes depend on each other, they are considered to indpendently contribute to the probability of the fruit being a banana hence why it is Naive')
print('')
print('QUESTION 6')
print('Difference between the 3 Naive Bayes Models:')
print('')
print('1.Gaussian : Deals with normally-distributed data i.e continuous e.g height of students in a class ')
print('2.Multinomial : Deals with data that has features which describe discrete frequency counts e.g number counts ')
print('3.Binomial : Deals with binary data e.g true/false, 0 or 1')


QUESTION 5
Naive Bayes makes the following assumption:

Attribute Independence: It assumes that the presence of a particular feature in a class is unrelated to the presence of any other feeture. 
         For example, a fruit may be considered a banana if it is elongated and yellow. Even if these attributes depend on each other, they are considered to indpendently contribute to the probability of the fruit being a banana hence why it is Naive

QUESTION 6
Difference between the 3 Naive Bayes Models:

1.Gaussian : Deals with normally-distributed data i.e continuous e.g height of students in a class 
2.Multinomial : Deals with data that has features which describe discrete frequency counts e.g number counts 
3.Binomial : Deals with binary data e.g true/false, 0 or 1
